### ISSUE TITLE
Markup error in `test.html`

### ISSUE THREAD

**Issue by dbohdan** [ChimeraCSS/ChimeraCSS#32]
In https://github.com/ChimeraCSS/ChimeraCSS/blob/fffd6f37ee43f6f7b902b63bd42c5fbe77400ae6/test.html#L108-L109 the closing tag closes a table instead of the div.

**Comment by J0hans1** [comment]
Good catch! Thank you for reporting this error. The problem has been solved per ChimeraCSS 1.1.3 💯
